spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: testuser
    password:
    url: jdbc:h2:mem:subway
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console